#!/bin/bash
SCRIPT_DIR=$(dirname "$0")

REMOTE_HOST=""
REMOTE_SSH_USER=""
REMOTE_MYSQL_HOST=""
REMOTE_MYSQL_USER=""
REMOTE_MYSQL_PASS=""
REMOTE_MYSQL_DB=""
REMOTE_DIR="/remote/"
LOCAL_MYSQL_HOST="localhost"
LOCAL_MYSQL_USER=""
LOCAL_MYSQL_PASS=""
LOCAL_MYSQL_DB=""
LOCAL_DIR="$SCRIPT_DIR/"
# CMS (typo3-6 | pmcms | wordpress | shopware)
CMS=""

# ===

$SCRIPT_DIR/download.sh $REMOTE_HOST $REMOTE_SSH_USER $REMOTE_MYSQL_HOST $REMOTE_MYSQL_USER $REMOTE_MYSQL_PASS $REMOTE_MYSQL_DB $REMOTE_DIR $LOCAL_MYSQL_HOST $LOCAL_MYSQL_USER $LOCAL_MYSQL_PASS $LOCAL_MYSQL_DB $LOCAL_DIR $CMS
